### ISSUE TITLE
Volume Issue

### ISSUE THREAD

**Issue by ADHDMAN** [protje/runelite-osrs-player-count#1]
I play OSRS with 5% volume and C Engineer Voice plugin at 170% is fine/ can hear clearly.
This one at 200% I can "Just" hear b0aty and if I put it anywhere over 200% it stops doing the voices notes... maybe worth looking into

**Comment by protje** [comment]
Sorry for the late reply, I am not active a lot on this account.

I am not sure what this has to do with my plugin? This plugin doesn't produce any sound.

**Comment by protje** [comment]
Since I did not get a reply on this issue I will close it.
